### ISSUE TITLE
🌏 Add Chinese Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#113]
Add Chinese as a supported language.

I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

**Comment by jkfliu** [comment]
Good to take this one! :)

**Comment by jkfliu** [comment]
Will submit pull request shortly to set up the language first, and see if i can figure out romanization later.

**Comment by jayehernandez** [comment]
Thanks @jkfliu! Let me know when you are done with the PR :)

**Comment by jkfliu** [comment]
Submitted, pls have a look.

Currently working on romanization, hope to complete and test tonight!

**Comment by jayehernandez** [comment]
Closed by #114
