### ISSUE TITLE
Clean-up of translations for "true" and "false" in various JSON files

### ISSUE THREAD

**Issue by jkfliu** [jayehernandez/letra-extension#119]
Something I noticed that happens during the conversion from Google sheets to JSON - the "true" and "false" values go awry (do not have double quotes), this doesn't impact the translations as such but if you're a bit OCD, should be cleaned up :)

Also the Japanese JSON entries for true/false should be fixed/removed.

$ egrep -i "true|false" *.json
chinese-simplified.json:        "translation": "false"
chinese-simplified.json:        "translation": "true"
french.json:    "translation": false
french.json:    "translation": true
german.json:    "translation": false
german.json:    "translation": true
hindi.json:    "translation": false
hindi.json:    "translation": true
indonesian.json:        "translation": false
indonesian.json:        "translation": true
japanese.json:    "word": "FALSE",
japanese.json:    "translation": false
japanese.json:    "word": "TRUE",
japanese.json:    "translation": true
korean.json:    "translation": false
korean.json:    "translation": true
spanish.json:    "translation": false
spanish.json:    "translation": true

**Comment by jkfliu** [comment]
Let me know if you want me to work on this - should be a quick fix.

**Comment by jayehernandez** [comment]
Thanks for noticing this, didn't pay much attention to this 😅 Good with fixing it, assigning you to this issue.

I fixed the Google Sheets template as well to avoid future issues with this.

**Comment by jkfliu** [comment]
PR submitted :)

**Comment by jayehernandez** [comment]
Closed by #126
