### ISSUE TITLE
✍️ Add a Quote - Great for Beginners!

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#13]
Is it your first time contributing to open source? First time coding something? This issue is perfect for you! 🥳

Letra features a small quote **about learning a new language** along with the word for the day, as shown here:
![Screenshot](https://github.com/jayehernandez/letra-extension/blob/master/docs/screenshots/main_screenshot.png?raw=true)

This is randomized everyday so that people can see a new quote that inspires them everyday!

### How To Contribute
1. Go to the [Contributing Guidelines](https://github.com/jayehernandez/letra-extension/blob/master/docs/how_to_contribute.md) to get started
2. The documentation for adding a new quote can be found [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_quote.md).
3. If at any part of the process you find yourself stuck, tweet me [@jayehernandez_](https://twitter.com/jayehernandez_), and we can go through it together!

### Some Reminders
- No need to wait for a confirmation if you'd like to add a quote.
- Just open up a pull request when you're done and **reference this issue**.

**Comment by imanishbarnwal** [comment]
Hello, @jayehernandez I want to work on this issue. How many quotes do I need to add here?

**Comment by jayehernandez** [comment]
> Hello, @jayehernandez I want to work on this issue. How many quotes do I need to add here?

@imanishbarnwal, no limit in the number of quotes you can add. Thanks for your PR! I'll be reviewing it in a bit.

**Comment by claire-thompson** [comment]
Hi! I’m a beginner interested in contributing a quote. I’ve read over the contributing guidelines and new quote documentation and am excited to get started. I’d welcome any additional pointers you have on how to proceed. Thank you!

**Comment by jayehernandez** [comment]
> Hi! I’m a beginner interested in contributing a quote. I’ve read over the contributing guidelines and new quote documentation and am excited to get started. I’d welcome any additional pointers you have on how to proceed. Thank you!

Hi @claire-thompson! Please to meet you :) Hope you can follow the checklist in the new quote documentation when submitting a pull request. Looking forward to your contribution!

**Comment by sakshi006** [comment]
Hi  @jayehernandez, i am a new contributor here. I'd like to work on this issue.

**Comment by Kvaibhav01** [comment]
Hey @sakshi006, you can take a look at the issue description to start!

> Is it your first time contributing to open source? First time coding something? This issue is perfect for you! 🥳
> 
> Letra features a small quote **about learning a new language** along with the word for the day, as shown here:
> [![Screenshot](https://github.com/jayehernandez/letra-extension/blob/master/docs/screenshots/main_screenshot.png?raw=true)](https://github.com/jayehernandez/letra-extension/blob/master/docs/screenshots/main_screenshot.png?raw=true&rgh-link-date=2020-05-17T04%3A09%3A16Z)
> 
> This is randomized everyday so that people can see a new quote that inspires them everyday!
> 
> ### How To Contribute
> 1. Go to the [Contributing Guidelines](https://github.com/jayehernandez/letra-extension/blob/improved-docs/docs/how_to_contribute.md?rgh-link-date=2020-05-17T04%3A09%3A16Z) to get started
> 2. The documentation for adding a new quote can be found [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_quote.md?rgh-link-date=2020-05-17T04%3A09%3A16Z).
> 3. If at any part of the process you find yourself stuck, tweet me [@jayehernandez_](https://twitter.com/jayehernandez_), and we can go through it together!
> 
> ### Some Reminders
> * No need to wait for a confirmation if you'd like to add a quote.
> * Just open up a pull request when you're done and **reference this issue**.

**Comment by pal05249** [comment]
Iam unable to open the contribution guidelines...it's says 404 error. Can anyone help?

**Comment by Kvaibhav01** [comment]
Hi @pal05249, thanks for pointing out. You can visit _[docs/how_to_contribute.md](https://github.com/jayehernandez/letra-extension/blob/master/docs/how_to_contribute.md)_ file to take a look,

@jayehernandez please update the link in this issue description.

**Comment by jayehernandez** [comment]
@pal05249 @Kvaibhav01 thanks for flagging, description has been updated accordingly.

**Comment by AARYAN-MAHENDRA** [comment]
Hello I would like to contribute.Its open for PRs right.

**Comment by gauthamdn** [comment]
@jayehernandez  i have added a quote and created a pull request 
#198

**Comment by RaithZx** [comment]
Hey, I've just read the  [Adding a quote documentation page](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_quote.md) but it says **"Try to add the quote in a random line"**, then in the checklist for valid PRs states: **The quote(s) added are in alphabetical order and not x duplicates.**.  
Seems to be contradictory or maybe I'm missing some point.
Hope I have explained myself.
Thanks.

**Comment by Kvaibhav01** [comment]
Hey @RaithZx so that there are no [merge conflicts](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-merge-conflicts) (when multiple contributors are working to fix the same issue or contribute to the same feature), we suggest adding the quote randomly i.e. not specifically towards the end of the file.

Of course, the quote author names are aligned alphabetically so you have to follow that. So, in all, you need to **put the quote according to the author's name (alphabetically) and not at the end.**

I hope it's clear why "Try to add the quote in a random line" is added?

**Comment by RaithZx** [comment]
Oh now I got it, thanks @Kvaibhav01! 
So we must place the quote in alphabetical order which eventually wil be as "random" placed.
