### ISSUE TITLE
Touch screen takes alot of touching ...to get workink done ...slows me down ..i would like the drop down not to cover my key board...on facial rec. make smother work and faster....

### ISSUE THREAD

**Issue by goldfinger18kt** [jayehernandez/letra-extension#134]
[NA](NA) **Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jayehernandez** [comment]
Looks like a bot issue, closing this. Please let me know if I'm wrong though.
