### ISSUE TITLE
No way to select a language?

### ISSUE THREAD

**Issue by notorious-sobriety** [jayehernandez/letra-extension#138]
**Is your feature request related to a problem? Please describe.**
How do I actually select a language I'm going to passively learn? I installed the extension and right now when I open a new tab it says "oops". When I go to to settings it doesn't have any inputs to select a language.

**Describe the solution you'd like**
I'd like a selectbox in the settings menu that would allow me to select a language.

**Describe alternatives you've considered**
I'm not sure I can think of any.

Additional context**
Do I actually need to install Node.js or something else just to use this extension? 

![Screenshot at 2020-06-04 15-01-19](https://user-images.githubusercontent.com/990640/83815589-5d9a5000-a675-11ea-979f-b47286207d04.png)

**Comment by jayehernandez** [comment]
Hey @notorious-sobriety, had a problem with the latest deploy to the Chrome web store. I fixed it already but that version is still pending approval from Chrome.

Hoping it gets accepted within the day. I’ll let you know when it does!

**Comment by notorious-sobriety** [comment]
Oh cool, thank you, I will wait for that!

**Comment by jayehernandez** [comment]
Hi there! Chrome accepted the new version, please update to `v1.0.8`, thank you. :)
