### ISSUE TITLE
🌏 Add Danish Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#153]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). 

Please go through the checklist so that you won’t miss anything!

**Comment by tobias1012** [comment]
Great, i'll get to work on the language translation

**Comment by tobias1012** [comment]
As this is starting to look stale i just wanted to document that i am in fact still active and working

**Comment by jayehernandez** [comment]
Thank you for the update @tobias1012!
