### ISSUE TITLE
🌍 Add Tamil Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#154]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

References #1

**Comment by kvharish** [comment]
Hi, @jayehernandez I can speak and read Tamil. I see no one has taken this up yet. Can I give it a try?

**Comment by jayehernandez** [comment]
Hi @kvharish sure, assigning this issue to you!

**Comment by kvharish** [comment]
Thanks, @jayehernandez started working on this.

**Comment by kvharish** [comment]
Hi, @jayehernandez I have created the pull request for Tamil language (#376)
