### ISSUE TITLE
🌏 Add Russian Language 

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#155]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

References #1

**Comment by notorious-sobriety** [comment]
I make a branch for my changes and when I'm done I make a pull request, right?

**Comment by notorious-sobriety** [comment]
Also do I set the "romanization" in languages.json to "true"? I see how it is done in the actual language files but for now none of the languages in languages.json have a romanization property so I'm unsure what values are appropriate.

**Comment by jayehernandez** [comment]
> I make a branch for my changes and when I'm done I make a pull request, right?

Yes this is correct! The process is the same as when you added a quote.

> Also do I set the "romanization" in languages.json to "true"? I see how it is done in the actual language files but for now none of the languages in languages.json have a romanization property so I'm unsure what values are appropriate.

No work in the `languges.json` file is needed for romanization, but you can check out `chinese-simplified.json` for an example of this.

**Comment by notorious-sobriety** [comment]
Oh ok. I asked because it was mentioned in the guide:

> romanization attribute: For selected languages only
> Example:
> 
> {
>   "german": {
>     "voice": "Deutsch Female",
>     "flag": "german",
>     "romanization": ""
>   }
> }
 
Not adding anything is easy :-)

**Comment by jayehernandez** [comment]
OH haha. Fixing that part in the guide now. Sorry!

**Comment by notorious-sobriety** [comment]
Hi Jaye! I'm mostly done with the bulk of translation. I have quite a number of items that have to be translated in two or three words or words with prepositions or set phrases - do you want those or should I scrap them? 
Also, as a side note, some of the words seem to be wide-used in English but their translations in Russian are a bit more obscure due to the fact I had to pick one translation of many (and not repeat myself). I'm not sure how to fix that except to go though that stuff again. But it seemed like something worth noting.
I'll try to create a script for romanization next and then upload everything and make a pull request.

**Comment by jayehernandez** [comment]
Thank you so much for working on this, Kate!

> Hi Jaye! I'm mostly done with the bulk of translation. I have quite a number of items that have to be translated in two or three words or words with prepositions or set phrases - do you want those or should I scrap them?

No worries if they have to be translated in two or three words, I think these will still be useful.

> Also, as a side note, some of the words seem to be wide-used in English but their translations in Russian are a bit more obscure due to the fact I had to pick one translation of many (and not repeat myself). I'm not sure how to fix that except to go though that stuff again. But it seemed like something worth noting.

If any of the words translated to Russian are unclear, it might be better to remove them. But if the translation is fine, I see no need to fix it anymore. I'll defer the decision for this to you!

**Comment by jayehernandez** [comment]
Closed by #180
