### ISSUE TITLE
🌏 Add Arabic Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#156]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

Refereences #1

**Comment by n3twk** [comment]
Thank you @jayehernandez , I'm working on it

**Comment by jayehernandez** [comment]
Closed by #164 164
