### ISSUE TITLE
🌏 Add Romanization for Korean

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#157]
Please follow the [Contributing Guidelines](https://github.com/jayehernandez/letra-extension/blob/master/docs/how_to_contribute.md) to see how you can fork this repo.

For this, since there is already a file in `server/data/words/korean.json`, you will only need to fill in the `romanization` attribute of each one.

Do let me know if you get stuck on any step.

**Comment by Philippians-4-13** [comment]
@jayehernandez I've got a question. 

Do I have to do this on korean.json? I've been doing my stuff on the link you pass me.

**Comment by Philippians-4-13** [comment]
I've pressed edit the fork and i did it there. Is that ok?

**Comment by Philippians-4-13** [comment]
Oh, now i've seen that doesn't work...

**Comment by jayehernandez** [comment]
Hey @Philippians-4-13 just saw your PR commenting there now!

**Comment by jayehernandez** [comment]
Closed by #158 158
