### ISSUE TITLE
🌍 Add Italian Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#185]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

References #1

**Comment by Astriduser** [comment]
Hi jayhernandez, i am a professional translator and interpreter and I do speak Italian. Do you still need help?

**Comment by jayehernandez** [comment]
Hey @Astriduser, yes some help on this would be appreciated! Would you like to take this on? I can assign it to you.

**Comment by PeppermintNDaisies** [comment]
Hello! I see this still needs to be done, I would like to work on this!

**Comment by jayehernandez** [comment]
Yes sure @PeppermintNDaisies! Assigning this to you :)

**Comment by PeppermintNDaisies** [comment]
Gret, thans @jayehernandez ! I submitted a PR for this issue #397

**Comment by jayehernandez** [comment]
Closed by #397. Thanks again, @PeppermintNDaisies!
