### ISSUE TITLE
intunewinapputil.exe

### ISSUE THREAD

**Issue by pandiangm** [jayehernandez/letra-extension#195]
Hi Team,

Could you please explain shall we create intune wrapper in Windows 7 64 bit using intunewinapputil.exe

Any system requirements for using intunewinapputil.exe

**Comment by Kvaibhav01** [comment]
You're still a bot. 😒 💢

**Comment by jayehernandez** [comment]
🤨🤨🤨

**Comment by thor174** [comment]
I am not a bot

pt., 19 cze 2020, 14:30 użytkownik Jaye Hernandez <notifications@github.com>
napisał:
