### ISSUE TITLE
🌍 Add Hindi Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#2]
Add Hindi as a supported language.

I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md).

Please go through the checklist so that you won’t miss anything!

**Comment by Kvaibhav01** [comment]
Hello, I would like to work on this issue 😁

**Comment by jayehernandez** [comment]
Assigned it to you, @Kvaibhav01! 😁
