### ISSUE TITLE
Null entries in hindi.json

### ISSUE THREAD

**Issue by gauthamdn** [jayehernandez/letra-extension#201]
**Is your feature request related to a problem? Please describe.**
There are null entries in the file hindi.json

**Describe the solution you'd like**
I will be able to update the missing entries and correct the hindi.json file

**Comment by Kvaibhav01** [comment]
Hi @gauthamdn, can you tell us which entries are null in _hindi.json_ by giving an example or two?

**Comment by gauthamdn** [comment]
hi @Kvaibhav01 , 

Examples below

1.null entries after the word adequate...
 {
    "word": "पर्याप्त",
    "translation": "adequate"
  },
  {
    "word": null,
    "translation": null
  },
  {
    "word": null,
    "translation": null
  },


2. After the word Admire
 {
    "word": "प्रशंसा करना",
    "translation": "admire"
  },
  {
    "word": null,
    "translation": null
  },

**Comment by gauthamdn** [comment]
Also, i actually took sometime to correct the null entries here. in the following [link ](https://github.com/gauthamdn/letra-extension/blob/master/server/data/words/hindi.json). 

Please review

**Comment by Kvaibhav01** [comment]
You've removed the null entries, that's good!

**Comment by gauthamdn** [comment]
@jayehernandez  i have opened a pull request # [204](https://github.com/jayehernandez/letra-extension/pull/204)
for the fix on hindi.json. 
https://github.com/jayehernandez/letra-extension/pull/204

pls review and merge

**Comment by jayehernandez** [comment]
Great job on the null entries! I reviewed your PR. Please let me know if you have done the requested changes for the quote since they are in a single PR.

**Comment by jayehernandez** [comment]
Forgot to close this issue! Closed by #204
