### ISSUE TITLE
Setting Option Click Issue

### ISSUE THREAD

**Issue by shubhsk88** [jayehernandez/letra-extension#210]
**Is your feature request related to a problem? Please describe.**
When I click on the setting the dropdown stays open until I click it on the setting button. 

**Describe the solution you'd like**
The settings dropdown should disappear once the user click anywhere else on the picture of extension

**Comment by jayehernandez** [comment]
Hi there @shubhsk88! Thanks for opening this issue.

I'm not sure if it's covered in #69, @Kvaibhav01 can you confirm? :)

If it's not, would you like to take this on, @shubhsk88?

**Comment by shubhsk88** [comment]
I can take this issue but I need to know what library are you using so I can take this issue

**Comment by Kvaibhav01** [comment]
Hi @shubhsk88, this issue is being worked on with a Snackbar indicating that the settings were saved as suggested in #69. @jayehernandez, you were about to make a PR regarding the Snackbar?

**Comment by shubhsk88** [comment]
https://www.loom.com/share/9ca929063b694bfeb3ebf348a95b924e
What I mean this I have to click on the snackbar again in order to disappear the setting while it should go away if I click anywhere else in the screen

**Comment by Kvaibhav01** [comment]
I can't see any snackbar in that video. It's in the todo list for the future versions of the extension. 😕

**Comment by shubhsk88** [comment]
Yeah but you got the bug that I am talking

**Comment by Kvaibhav01** [comment]
Yes, I see what you're talking, I and @jayehernandez are in the process of working to fix that bug. If for some reason it's not done, we can give it to you. Let's wait for Jaye to reply.

**Comment by jayehernandez** [comment]
Ah okay, I got what you were trying to say @shubhsk88. 

I didn’t realize this was also a part of the issue @Kvaibhav01 already opened. Particularly this part:

> _whenever we click outside the pane_

Hope it’s okay that I’ll be closing this issue now, as it seems it is a duplicate. Further updates will be in #69.
