### ISSUE TITLE
Making the Sideoption as dropdown to switch between languages

### ISSUE THREAD

**Issue by shubhsk88** [jayehernandez/letra-extension#211]
**Is your feature request related to a problem? Please describe.**
In the left side of the screen, there is a language flag shows which doesn't support the dropdown as if I selected multiple languages to learn, It shows only one language
**Describe the solution you'd like**
We can add the feature like to dropdown who have selected multiple languages to learn we can provide like random, german, Korean, etc so the user can basically have the flexibility to see the word in a language they want.

**Comment by jayehernandez** [comment]
Good idea! Although I'm not sure if it should be added as an option when clicking the flag on the left side of the screen?

The flag is meant to be a marker of what the current word of the day is. Maybe it's better to add this to the refresh button instead? What do you think?

**Comment by shubhsk88** [comment]
I mean we might have to look for the way that users can switch with the language. The other option is that what about when user opens a new tab it will come up with the new word and if the user switches the language then the next word should be on that languages I think that will be a good enhancement

**Comment by jayehernandez** [comment]
For context, a new word from a random language (based on those the user selected) is chosen everyday.

Changing the word for every new tab might not be a good solution considering the fact that they should be seeing the same word for that day to retain memory of it.

I can whip up a quick mock-up for refreshing the word in the user’s chosen language. I’m thinking this can be a pop-up under the refresh button. Then, as suggested a dropdown of the user’s selected languages will be here).

After the mocks are done, would you want to take this one on? We’re using VueJS for development, no libraries for the dropdown or pop-up are currently in use too.

**Comment by shubhsk88** [comment]
Yeah I will be happy to take the issue but can we discuss this in brief so I have the gist of it

**Comment by jayehernandez** [comment]
Hey there @shubhsk88, didn't have the time to do the mock-up for this but are you still willing to take this on? Let me know!

**Comment by shubhsk88** [comment]
Yeah sure we can discuss it if you have time

**Comment by shubhsk88** [comment]
Yeah, I would be happy to take this and I was thinking that if we can give a user like an option to decide himself like after how much time he wants the word to be refreshed, what do you think of that?
I am little new to vuejs and experienced in react js but I will try  to solve that issue

**Comment by jayehernandez** [comment]
> Yeah, I would be happy to take this and I was thinking that if we can give a user like an option to decide himself like after how much time he wants the word to be refreshed, what do you think of that?
> I am little new to vuejs and experienced in react js but I will try to solve that issue

@shubhsk88 To avoid adding complexity, I think we won’t need that option for now! Good with doing the dropdown issue first. I’ll assign you to this issue!

**Comment by DieBrise** [comment]
Hey @jayehernandez @shubhsk88 I'd like to work on this issue, but I need to clarify one thing: 

Should the flag on the top-left show a dropdown of all available languages, or just languages the user has selected from the options on the top-right?

Right now, I have a dropdown working with all options. I'd like to be sure of the functionality above before I begin designing.

**Comment by jayehernandez** [comment]
Hey @DieBrise, it should only show the languages the user chose to limit the options. :)

@shubhsk88 want to check if you are still working on this?

**Comment by shubhsk88** [comment]
@jayehernandez  thanks for the followup.I am busy with my personal issues. So if somebody wants to take this issue. It's fine

**Comment by jayehernandez** [comment]
Closed by #301
