### ISSUE TITLE
Adding Most common word deck in the database and use real voice instead of voice api

### ISSUE THREAD

**Issue by shubhsk88** [jayehernandez/letra-extension#215]
**Is your feature request related to a problem? Please describe.**
The extension doesn't show common word often and sometimes it shows weird like a "battery" which very rarely gets used by the people learning languages  and pronunciation of these words is even terrible so it would be a good enhancement if we can replace those word with most commonly used words

**Describe the solution you'd like**
We can use the deck from the popular app which has the collection of most commonly used words with the real voice(I can help with the languages I am learning) and this would help to learn the more common word and see in their tab

**Comment by jayehernandez** [comment]
Understandable concerns! 

1. Word deck
I used a reference for the 3000 most used words. This repository is based on the [Oxford 3000](https://www.oxfordlearnersdictionaries.com/us/wordlist/) and battery is actually a common word used. What deck do you suggest we use? I feel like this is enough?

2. Real Voice vs Voice API
This seems like a hard feature that may be out of scope for this repo. At the top of my head, this involves:
- finding people who speak the language fluently (ideally, natively too) to nail the correct accent (current count of languages is 12)
- having quality equipment to record the words
- making sure the recorded words are correct, by cross-checking with _another_ person who speaks the language fluently
- compiling all the sound files and storing them in the server

The voice API provides a simple and easy way to do this with **consistent** quality, making adding a new language as a contribution easier and faster for others who would like to help. 

Let me know your thoughts on any of these two concerns.

**Comment by shubhsk88** [comment]
The voice api pronunciation is really horrible and We can use the deck that people actually use to learn language not some oxford common word Personally I think those decks are more helpful and they usually come with the voice I am suggesting to look after some deck that i think is much far better 
- [Memrise](https://www.memrise.com/course/1614/1000-most-common-korean-words/) 
-[Anki decks](https://ankiweb.net/shared/decks/korean)
We can just pick out the best one from each language in that way we don't even have to go through the voice api

**Comment by jayehernandez** [comment]
I skimmed through a few of the deck words and they seem to include stuff like greetings for beginners to more intermediate phrases and words for home, travel, food, etc.

This app was designed to serve as a **supplementary** guide to the apps you mentioned above though. So they use their own word decks for phrases like “How are you?” and it’s their job to help you learn those.

Letra’s job then is to give you _other_ words that may not be covered by your primary language learning app, but are still essential to learning a new language. I feel like the 3000 most common words is the way to do this.

**Comment by shubhsk88** [comment]
Can we discuss this I didn't think you got my point

**Comment by jayehernandez** [comment]
I think it's quite clear what your feature request is but let me know what I got wrong
