### ISSUE TITLE
Showing language name on hover over flag (Feature Request)

### ISSUE THREAD

**Issue by RathiRohit** [jayehernandez/letra-extension#237]
First of all thanks for such a beautiful extension. This is now on top of my "new tab extensions" list 🤩 .

One thing I found that can be very helpful is showing language name along with Flag on left corner.
To not to clutter existing content on the screen, language name can be shown on hovering over flag. Which will hide back when mouse is moved out.

Right now one has to guess the language of the word from flag, which I feel is very counter-intuitive. This becomes especially problematic when multiple languages are selected in settings.

PS: I would be more than happy to work over this myself & raise a PR (if this seems valid feature to maintainers) 😄

**Comment by jayehernandez** [comment]
Agree with this! It’s not easy to memorize the flags so this will provide more context to the user. Assigning you to this issue. Please let me know if you need help! :)

**Comment by jayehernandez** [comment]
Closing this issue!
