### ISSUE TITLE
🌍 Add Afrikaans Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#247]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

References #1

**Comment by Wanrick** [comment]
Thank you for the new Issue @jayehernandez.

**Comment by jayehernandez** [comment]
Adding to the next release!
