### ISSUE TITLE
Wrong Flag for Bangla Language 

### ISSUE THREAD

**Issue by ponickkhan** [jayehernandez/letra-extension#290]
bangla flag should be this 🇧🇩  instead of this 🇧🇳

**Comment by jayehernandez** [comment]
Thanks for flagging this, @ponickkhan! Do you want to work on changing this? If not I’ll be taking it on.

**Comment by ponickkhan** [comment]
> Thanks for flagging this, @ponickkhan! Do you want to work on changing this? If not I’ll be taking it on.

@jayehernandez  i have already made a pull request on this

**Comment by jayehernandez** [comment]
Closed by #294
