### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by zunamidev** [jayehernandez/letra-extension#293]
A setting to change the background image to a solid color. Like this
![image](https://user-images.githubusercontent.com/44585887/94295121-122bea80-ff61-11ea-8916-ac63a612f93d.png)

I already created one PR for this
#292 

I hope this is description is okay, it's my first PR to open source.

**Comment by jayehernandez** [comment]
Yup! Would be glad to have this a s a feature to also help with lowering the requests to Unsplash, I'll be reviewing your PR on it.
