### ISSUE TITLE
How I can contribute to this repository for translate Japanese?(number format)

### ISSUE THREAD

**Issue by perpouh** [jayehernandez/letra-extension#308]
Hello.
I saw https://dev.to/devteam/whos-looking-for-collaborators-hacktoberfest-2020-jl89

I want to contribute to this repository for translation Japanese.

but I'm wondering which one to unify japanese.json with numeral

example:

漢数字(kan-suji, kanji numeral) used for vertical writing(mainly).
```
  {
    "word": "四",
    "romanization": "",
    "translation": "four"
  },
```

アラビア数字(Arabia-suji, Arabic numeral) used for horizontal writing(mainly).
```
  {
    "word": "15",
    "romanization": "",
    "translation": "fifteen"
  },
```

I think anyone can understand Arabic numerals without having to write them, so can I unify them with kanji numerals?

There are at least 3 ways to write even with only "15". LOL
>十五(normal, poplar, standard)
>一五(used for newspaper with age, date etc.)
>拾五(used for accounting, money, numbering of manga etc.)

wondering romanization too...:shrug:
jugo
juugo
ju-go

**Comment by perpouh** [comment]
I'm going to remove unnecessary "です(desu)" "ます(masu)" for the time being.

**Comment by jayehernandez** [comment]
Hey @perpouh, thanks for the interest in contributing!

I'm not that familiar with Japanese, but I think we can go with the normal and standard way? So that beginners trying to learn the language will be most familiar with the popular option.

What do you think?

**Comment by perpouh** [comment]
If the purpose is learning to write, it is better to use a general notation.
But if the purpose is learning to read, I thought it would be nice if I could show that these are idioms with the same meaning(十五、一五、拾五

I'm not that familiar with English, sorry if it's hard to read.

**Comment by jayehernandez** [comment]
Ah I understand, we can start with the general notation for now, if that's okay @perpouh. There's no support yet for alternate translations so the standard way would be ok.
