### ISSUE TITLE
Save button is unclickable on smaller screens

### ISSUE THREAD

**Issue by singleparadox** [jayehernandez/letra-extension#312]
**Problem**: Save button is unclickable on smaller screens

**Solution**: It seems that the "time" is overlapping the options menu. changing the z-index of  .options-menu from 2 to 4 fixes the issue. 

![image](https://user-images.githubusercontent.com/29853589/94774397-6ebf5780-03f0-11eb-84d0-3b4b5b2ea5d0.png)

**Comment by singleparadox** [comment]
Sent a PR #313 :)

**Comment by jayehernandez** [comment]
Thanks for flagging this, and making the fix for it! :)

**Comment by singleparadox** [comment]
Welcome! I saw that my PR was merged. Closing this.
