### ISSUE TITLE
Add Swahili Language

### ISSUE THREAD

**Issue by BaharaJr** [jayehernandez/letra-extension#359]
I would love to contribute by adding the Swahili language that is widely used in East and Central Africa. The Swahili language is the official language for  [Tanzania](https://en.wikipedia.org/wiki/Languages_of_Tanzania) and is vastly used in [Kenya, Uganda, DRC, Sudan, etc](https://en.wikipedia.org/wiki/Swahili_language). The language is rich in features and dialects are spoken in other countries like Comoros.

I have gone through the [contributions guide](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md) and [checklist](https://github.com/jayehernandez/letra-extension/issues/1) and I would love to add the language.

**Comment by jayehernandez** [comment]
Assigning you to this issue, @BaharaJr! Please let me know if you need any help.

**Comment by BaharaJr** [comment]
I will reach out for any further help needed @jayehernandez

**Comment by xinnks** [comment]
@BaharaJr If you would like some more hands on the Swahili translation, I'd be pleased assist.

**Comment by BaharaJr** [comment]
Hey, @xinnks let's catch up and get this ship sailing.  I sent you a message on WhatsApp

**Comment by jayehernandez** [comment]
Assigning this issue to both of you @BaharaJr and @xinnks. Thank you! :) References #1
