### ISSUE TITLE
Word [H1] is overlapping with the H2

### ISSUE THREAD

**Issue by therohitdas** [jayehernandez/letra-extension#364]
During this COVID times, we should maintain social distancing. Words overlapping each other sends the wrong message.

Yes! I am Kidding.

I am talking about this overlap. 
Language - Bengali

![Screenshot (17)](https://user-images.githubusercontent.com/43847374/94993744-c3113580-05b0-11eb-8e7c-c7c7c7217f0b.png)
![Screenshot (16)](https://user-images.githubusercontent.com/43847374/94993747-c5738f80-05b0-11eb-94cb-4109637e9444.png)

It can also happen when language is HINDI.

I am submitting a PR to fix it.

**Comment by jayehernandez** [comment]
LOL @ the intro 🤣 thanks for the laugh and the PR!!
