### ISSUE TITLE
📄 README changes

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#369]
Super grateful for everyone who has contributed to this repo so far. We’re currently seeing an influx of new PRs too since it’s Hacktoberfest! 🥳

The README is the go to place for new contributors. It’s the first impression of a repo. The current one works okay, but I’ve noticed that the all contributors section has been a bit too crowded since there are so many contributors. Which is a good thing!! Grateful for everyone that made Letra what it is now.

With this though, it has been decided that contributions related to **content** (mostly for adding quotes) will not be included in the all contributors section. But don’t worry! They will still be counted to the overall contributors count and will be included in this [page](https://github.com/jayehernandez/letra-extension/graphs/contributors)!

I’ll be cleaning up this section and linking the PR to this issue as well! Self-assigning it for accountability.

_A note on Hacktoberfest:_
Please be patient in having your PR reviewed, October has been a busy month for me, the owner of this repo. If you see @Kvaibhav01 comment on yours, please follow his suggestions as he is also helping out with reviewing the PRs! 🙏

**Comment by Kvaibhav01** [comment]
I hope this idea goes well Jaye. Thank you for the mention and for letting everyone know about this. 😁

**Comment by jayehernandez** [comment]
Closed by #432 and #433!
