### ISSUE TITLE
Add link to Support Page in the error page.

### ISSUE THREAD

**Issue by therohitdas** [jayehernandez/letra-extension#375]
Currently when users see the error page, 
![Screenshot (21)](https://user-images.githubusercontent.com/43847374/95008304-4032be00-0636-11eb-86a1-43195daa9dd2.png)
They are asked to go to the support tab.

I suggest adding a **link to the support tab.**

It will make the support tab accessible to users and decrease frustration.
Not having the link is frustrating because the user does not which support tab you are talking about.

Please send me the link to the support tab. So that I can start working on it.

**Comment by jayehernandez** [comment]
This makes sense! There's no direct link to this though, but you can go to it by clicking on [this](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) link!

**Comment by therohitdas** [comment]
Okay, I can write something like - 
"Please go to the [support tab](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) of the extension if this continues!"

or create a button saying `take me to support tab`
