### ISSUE TITLE
🌍 Add Polish Language

### ISSUE THREAD

**Issue by sthiepaan** [jayehernandez/letra-extension#388]
Hello everyone 👋,
I would like to contribute by adding Polish language translations. It is the official language of Poland 🇵🇱 Some people say that Polish language is one of the hardest but from my point of view it is _"easy to learn, hard to master"_ 😛

I checked #1 and have gone through the guideline and checklist for [Adding a New Language](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md).

I would love to add a new language into _Letra_ 😊😊😊
Let me know what you think! ✌️

**Comment by jayehernandez** [comment]
Thank you for this!!! I will be looking at your PR shortly. 🥳
