### ISSUE TITLE
.Env Issue While Following Installation Guide

### ISSUE THREAD

**Issue by tbarland77** [jayehernandez/letra-extension#40]
Hey @jayehernandez first thanks for accepting my quote PR that was my first real contribution to an open source project! Anyway, I saw you had added an installation guide (great guide btw!) for Letra and I decided to follow along. After finishing the guide, I kept getting an error locally. Upon adding some console logs, I noticed my env keys were returning undefined. After reading a post on stack-overflow (https://stackoverflow.com/questions/26973484/how-do-i-setup-the-dotenv-file-in-node-js#43973629) it appeared the below two commands were adding double quotes to the .envs:

> echo "PORT=3100" >> .env
> echo "VUE_APP_API_URL=http://localhost:3100" >> .env

This caused the values to not be picked up. Removing the double quotes and running the commands like this:

> echo PORT=3100 >> .env
> echo VUE_APP_API_URL=http://localhost:3100 >> .env

Fixed the issue for me and I am no longer seeing any errors. Just thought I would pass this information along in case anyone else gets stuck!

**Comment by jayehernandez** [comment]
Thank you for letting me know about this @tbarland77!! 🙏🏻

Glad the guide helped you! I'll be updating the guide to remove the double quotes. 😄

**Comment by jayehernandez** [comment]
Just removed it. Thank you again, appreciate it!
