### ISSUE TITLE
Issue with coverage while using rewire with jest

### ISSUE THREAD

**Issue by kvharish** [jayehernandez/letra-extension#400]
Hi, @jayehernandez @Kvaibhav01 I am currently looking to add some tests to boost the coverage. I notice that rewire is being used in server/test/letra.test.js in order to test internal functions in server/routes/letra.js. There is an ongoing issue with coverage, not updating while using rewire with jest.

https://github.com/facebook/jest/issues/8871
https://github.com/jhnns/rewire/issues/145

Not sure if this has been already discussed here before. I would like to know if we have any alternate approach already in mind?

**Comment by jayehernandez** [comment]
Hey @kvharish! I haven't actually considered any alternative approach yet, do you have something in mind?
