### ISSUE TITLE
Thai Flag is Missing in README.md

### ISSUE THREAD

**Issue by ponickkhan** [jayehernandez/letra-extension#402]
Thai flag should be this 🇹🇭 instead of ᴛʜ

**Comment by Kvaibhav01** [comment]
Hi there, this change has already been made as a PR by @kvharish [#381](https://github.com/jayehernandez/letra-extension/pull/381)

**Comment by jayehernandez** [comment]
Closed by #381, thanks for reporting @ponickkhan and checking @Kvaibhav01!
