### ISSUE TITLE
🌏 Add Greek Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#417]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

References #1

**Comment by elenakout** [comment]
I already start working on it :)

**Comment by jayehernandez** [comment]
Assigned you to the issue @elenakout!
