### ISSUE TITLE
🌏 Add Croatian Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#418]
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

References #1

**Comment by mViolet** [comment]
Thank you! I’d love to work on this

**Comment by jayehernandez** [comment]
Assigning you to this @mViolet!
