### ISSUE TITLE
Update Date & Time Without Refresh

### ISSUE THREAD

**Issue by tbarland77** [jayehernandez/letra-extension#42]
Hi @jayehernandez not to open another issue so soon, :sweat_smile: but I saw a card here: https://github.com/jayehernandez/letra-extension/projects/1#card-38630812 for updating the date and time without having to do a refresh and was wondering if it's not currently being worked on could I pick it up? I'm not super familiar with Vue although I have worked with it a little bit in the past.  Anyway, I would love to work on the issue and contribute some code if it's not already actively being worked on!

**Comment by jayehernandez** [comment]
Hey @tbarland77 totally fine! Thank you for looking at the projects.

This card is reserved for now, so sorry for not making it clear but I'll let you know if ever it is free. Also added some other improvements that might interest you. I can help out if ever you decide to work on one and get stuck with something.

**Comment by tbarland77** [comment]
No problem! I'd love to be able to contribute more and figured looking at the projects tab would be a good place to start.

Okay, that one is reserved got it. I also see that is the only one now with a reserved tag. So anyone can work on the other ones right? I think I could try working on adding the contribute to GitHub link inside the options menu one. Although I have a question or two about that... 

Does the options menu refer to that gear icon where you can swap what language you're learning? If so, does that mean the card would be just to add a new section in the menu, some text, and a link to Letra's GitHub page? Just want to make sure I understand the card before picking it up and working on it. Thanks for offering to help too @jayehernandez! I'll be sure to reach out if I ever happen to get struck on something.

**Comment by jayehernandez** [comment]
Confirming that the others are free for all!

WIth the contribute to Github link, I was thinking of adding a "Contribute to Github" link inside `Options.vue` (the place where you choose the languages) for now. Here's something quick I created on Figma to help visualize:
<img width="256" alt="Screen Shot 2020-05-23 at 10 42 52 PM" src="https://user-images.githubusercontent.com/13959651/82733491-c8c75680-9d46-11ea-9f87-492b456f64ce.png">

Since not everyone who may use the extension is a developer, I didn't want it to be a main focus (putting a link in the main page) so I thought it's better to just add it here. If you have some suggestions, do tell. Open to other ideas!

Let me know if you'd like to take this on given the context above so I can convert the card into an issue and assign it to you.

**Comment by tbarland77** [comment]
This helps out a lot thanks for the visual! Yeah, I can see not wanting this on the main page since it's not really something that would add much value to non-developer users. As far as suggestions, I don't think I have any... Having it right below the save button seems like a good spot to me. Anyway, I would definitely be interested in picking this up, and having the issue assigned to me. Looks like I'll get to learn a bit of Pug along the way too so it should be interesting.

**Comment by jayehernandez** [comment]
Great, really appreciate it! I added a new issue for this #48, hope you can comment there so I can assign it to you.

Also yes to learning some Pug templating! Just occurred to me that I haven't really mentioned that anywhere, thank you for the reminder 😅Pug's really great for lazy people like me haha, I hope you have fun using it.

**Comment by tbarland77** [comment]
No problem! Glad to help out more! Awesome, I'll add a comment over there too. I also saved the above visual already if we want to just close this issue? Looking forward to learning a bit of it for sure. Only tempting I've really worked with before was Mustache. Haha, if It's good for lazy people I'm sure I'll love it too! :satisfied:

**Comment by jayehernandez** [comment]
Ooohh I have to try Mustache! I'll be closing this issue now, I'll also add the visual in the new issue just for documentation. Thank you so much!!
