### ISSUE TITLE
🖥 Change languages options to use a multiple select dropdown

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#434]
**Is your feature request related to a problem? Please describe.**
The list of languages is getting way too long 😅
<img width="216" alt="Screen Shot 2020-10-09 at 1 17 33 PM" src="https://user-images.githubusercontent.com/13959651/95677948-bec1c980-0bfb-11eb-9f42-06de7d594591.png">

**Describe the solution you'd like**
Use some sort of multiple select dropdown for choosing languages instead of checkboxes.

**Comment by reginaalyssa** [comment]
Hope it's okay that I take this on. :)

**Comment by jayehernandez** [comment]
Assigning this to you @reginaalyssa :)

**Comment by jayehernandez** [comment]
Closed by #438
