### ISSUE TITLE
Broken Link for Contributing Guidelines

### ISSUE THREAD

**Issue by seryafarma** [jayehernandez/letra-extension#45]
For adding new quotes as shown in #13
The link to the *Contributing Guidelines* is broken. It results in a 404 page.

**Comment by seryafarma** [comment]
https://github.com/jayehernandez/letra-extension/blob/improved-docs/docs/how_to_contribute.md

**Comment by jayehernandez** [comment]
Thank you for flagging this @seryafarma!! Just deployed a fix for it :)
