### ISSUE TITLE
🛠 Unit Test - Alphabetically Ordered Quotes

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#475]
One of the guidelines for adding a new quote is to make sure that it is added in alphabetical order by author's first name.

Currently, checking this is done manually but we can add an automated test for this in [this](https://github.com/jayehernandez/letra-extension/blob/master/server/test/quotes.test.js) file so that it's flagged automatically.

If you'd like to work on this, please let me know!

**Comment by SNIGDHA2654** [comment]
I'd like to work on this issue!

**Comment by jayehernandez** [comment]
Assigning this to you, @SNIGDHA2654!

**Comment by charanjit-singh** [comment]
@SNIGDHA2654 any progress or should I take over this issue?

**Comment by SNIGDHA2654** [comment]
You can take over.

**Comment by jayehernandez** [comment]
Closing this issue, @Koddi-Evangelista was able to create a PR for this!
