### ISSUE TITLE
Add Swedish language

### ISSUE THREAD

**Issue by codefunlearn** [jayehernandez/letra-extension#477]
Hello. 

**Describe the solution you'd like**

I speak Swedish and can [add it as a new langage ](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md).

For _hacktoberfest_ as a _good first issue_.

Regards

**Comment by Kvaibhav01** [comment]
Hey, thanks for your interest but before opening a issue regarding adding a new language please take a look at the [already opened one](https://github.com/jayehernandez/letra-extension/issues/1#issue-612543239) by the repository owner. The instructions are written there.

Also, [Swedish is already supported](https://github.com/jayehernandez/letra-extension#-supported-languages) and is mentioned in the _README.md_ file of the repo.

You can work on [other open issues](https://github.com/jayehernandez/letra-extension/issues?q=is%3Aopen+is%3Aissue).

**Comment by codefunlearn** [comment]
Hi @Kvaibhav01 
Thank you for the feedback. (I thought perhaps one could add words for these supported languages.)
Feel free to close the issue.
