### ISSUE TITLE
Add Contribute on Github link inside the Options Menu

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#48]
Add a "Contribute on Github" link right below the Save button of the Options Menu

<img width="256" alt="Screen Shot 2020-05-23 at 10 42 52 PM" src="https://user-images.githubusercontent.com/13959651/82734612-a9342c00-9d4e-11ea-94cd-0d6d5c3f5fa8.png">

Discussed specs in Issue #42

**Comment by tbarland77** [comment]
Hey @jayehernandez as mentioned in the other thread / issue I'd love to pick this up! Can you assign it to me?

**Comment by jayehernandez** [comment]
Assigned it to you @tbarland77!! Good luck 🎉

**Comment by tbarland77** [comment]
Thanks! I'll reach out if I run into any issues or questions along the way too.

**Comment by jayehernandez** [comment]
Closed by #51
