### ISSUE TITLE
Arranging quotes Alphabetically

### ISSUE THREAD

**Issue by profread** [jayehernandez/letra-extension#516]
Will like to know if there is an automatic way to arrange quotes in alphabetical order.
Rather than arranging quotes manually in `quotes.json.`

Are there some tests that can be run to check this?

**Comment by jayehernandez** [comment]
This is actually already implemented in #475, do you have any other suggestions for this?

**Comment by jayehernandez** [comment]
Closing this issue, feel free to reopen!
