### ISSUE TITLE
🌏 Add Filipino Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#52]
Responsive Voice supports Filipino as a language!!

Creating the branch `feature/filipino-language` for this 🙌🏻

Base file for filipino words: https://docs.google.com/spreadsheets/d/1SryOwlrrzBPsUUbMRPwIomqnSPgNpw9Xf1CqOL7VJqM/edit#gid=0

Here's the [guide](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md) as well for adding new language.

**Comment by danaredena** [comment]
Game 💛

**Comment by WarenGonzaga** [comment]
@jayehernandez Is there anything else I can help? You can assign this to me.

**Comment by jayehernandez** [comment]
Already completed by @Koddi-Evangelista in PRs: #349, #390, #443, #462
