### ISSUE TITLE
add romanization below the word

### ISSUE THREAD

**Issue by kimberrypi** [jayehernandez/letra-extension#54]
**Is your feature request related to a problem? Please describe.**
The characters for Chinese, Japanese, and Korean are challenging to associate with their English translations. 

**Describe the solution you'd like**
<img width="1287" alt="Screen Shot 2020-05-24 at 5 22 38 PM" src="https://user-images.githubusercontent.com/20434382/82750513-3923b580-9de3-11ea-8bb9-0435f64e5a22.png">

Add a romanization line for languages with characters. This will help people who like to learn reading aside from speaking.

Please comment on the styling. tq!

**Comment by jayehernandez** [comment]
Hii Kim!! Thanks for starting this.

Just made a few changes with the styling but if you want to work on it go ahead!!
![image 3](https://user-images.githubusercontent.com/13959651/82750708-7b012b80-9de4-11ea-8583-e3d22a53922a.png)

**Comment by jayehernandez** [comment]
Closed by #55
