### ISSUE TITLE
Collab for Hindi

### ISSUE THREAD

**Issue by shardon889** [jayehernandez/letra-extension#582]
Hey, I would like to work for Hindi or Punjabi if there is an option,  It would be great contributing to this project

**Comment by Kvaibhav01** [comment]
Hey @shardon889, the support for the [Hindi language is already there](https://github.com/jayehernandez/letra-extension#-supported-languages). 

As for any other contributions, the project is [currently on vacation mode](https://github.com/jayehernandez/letra-extension#readme) (paused). So until it resumes, we can't say anything.

Thanks for your issue though, you can close it for now. Maybe we can re-open it later on. Thanks!
