### ISSUE TITLE
make this with programming languages

### ISSUE THREAD

**Issue by StarNumber12046** [jayehernandez/letra-extension#619]
**Is your feature request related to a problem? Please describe.**
I would really like to see this ported to programming languages

**Describe the solution you'd like**
Learn something of a programming language everytime you open a new tab

**Describe alternatives you've considered**
IDK, maybe changing project files a bit (I'll try to fork this and do it)

**Additional context**
nothing :/

**Comment by jayehernandez** [comment]
@StarNumber12046 since this project focuses on foreign languages, that seems like a great fork to work on if you would like! You're free to use this as your base as long as you give credit that you used it as such. If there's nothing else, I'll be closing this issue! :)
