### ISSUE TITLE
New Words for every New Tab

### ISSUE THREAD

**Issue by seryafarma** [jayehernandez/letra-extension#66]
Hello,
How about this feature? I think it would be a nice addition.

It would be very nice when I open new tabs, I get presented with different words than the first one. Now if I open 3 tabs, I get the same three words.

**Comment by jayehernandez** [comment]
Hey @seryafarma, great work on the 🇮🇩 translation!

This is actually the intended behavior. 😅 The idea behind it is that you’ll be seeing the word throughout the day, which increases the chances of you actually learning the word and memorizing it. Passive learning!

It resets every 12 AM though, so one new word per day. Hope this clarifies!

**Comment by seryafarma** [comment]
Ah that is how it is? Step by step learning indeed.

**Comment by seryafarma** [comment]
I will close this request then 😌
