### ISSUE TITLE
🐛 Close the settings pane after selection

### ISSUE THREAD

**Issue by Kvaibhav01** [jayehernandez/letra-extension#69]
Currently, when we select a language(s) from the settings pane and hit 'Save', it doesn't close. 

What we need is a fix in which this _closes as soon as the user selects the language(s)_ or _whenever we click outside the pane_.

**Comment by jayehernandez** [comment]
Thanks for opening this issue @Kvaibhav01! 💯

The behavior now is that it doesn't close so that "Saved changes!" message can be seen, alerting the user that the languages they chose were saved.

If we were to close the settings pane, how do you propose to alert the user that the changes were saved?

**Comment by Kvaibhav01** [comment]
There can be several ways:

1. The pane automatically closes _x_ seconds after the "Saved changes!" text is displayed. Typically 5 seconds.

2. We can have a short snackbar like [Snackbars in Vuetify](https://vuetifyjs.com/en/components/snackbars/#snackbars) or [`vuejs-snackbar`](https://livelybone.github.io/vue/vuejs-snackbar/) to display the message to the user.

3. [Something different...] Just like there is a voice feature next to the translated word, the voice can say "Your changes were saved" along with the message displayed in the form of above two points. This will ensure accessibility.

**Comment by jayehernandez** [comment]
Great ideas! Leaning towards suggestion number two. Opening this issue up for anyone who would like to work on it. :)

**Comment by Kvaibhav01** [comment]
I would like to give it a try after I finish the [automatic time refresh](https://github.com/jayehernandez/letra-extension/projects/1#card-38630812) issue.

**Comment by jayehernandez** [comment]
Sure! I'll assign the issue to you for now!

**Comment by Kellygray31** [comment]
Fuuyhh

**Comment by Kellygray31** [comment]
Ghghj

**Comment by jayehernandez** [comment]
Closed by #241 :D
