### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by tbarland77** [jayehernandez/letra-extension#79]
Hi, @jayehernandez I saw your last comment on my PR for #48 and thought I would open up a new issue for us to brainstorm about adding unit tests to Letra. First I was thinking it might be good to divide this one into two separate issues. The first issue could be to add the foundation for unit testing in Letra. This could include:

1. Adding Jest (if we decide to go with Jest) to both the client and server
2. Creating a few unit tests for both the server and the client
3. Creating / updating documentation on how to run the unit tests for both the client and the server

I think this would give us a good base to start with. After that, I think the second issue could be similar to #13. Except instead of adding a quote contributors could add a missing unit test instead. We could likely use a code coverage report to help us in that regard. I also think just having one issue for adding all the tests at once would be a rather hefty undertaking and this way it breaks it up a bit and opens the door for more contributions.

As far as unit testing Vue I'm not really familiar with it either... Most of my unit testing experience comes from writing unit tests for Angular code. I'd definitely be interested though in giving it a go and learning along the way. Anyway, I would love to hear your thoughts on this idea!

**Comment by jayehernandez** [comment]
Hey @tbarland77, thanks for initiating this!

Agree with the steps you suggested. This issue can be for setting up the testing tool of choice. I'm good with going with Jest! The docs look great and there are simple guides we can follow to add it both to the client and server. Would you be interested in doing this?

After setting up the first few tests (in another issue), we can even require this to run every time someone initiates a PR. I'd be happy to help out in this regard, we can start out with the server code as well for this, as most of the PRs right now are server side.

**Comment by tbarland77** [comment]
Sure, I would love to work on this! So for this issue, it would be just adding Jest to both the client and server then adding the first few unit tests would be covered in a separate issue? I just want to make sure I'm following what the specs should be for this first issue.

Having the tests run every time someone initiates a PR would be good. That way we could help ensure nothing was accidentally broken. The server definitely does seem to be the most active right now with people contributing quotes and working on adding more languages so that makes sense to me.

**Comment by jayehernandez** [comment]
Yes, this issue will only be for adding Jest to the client and server!

**Comment by tbarland77** [comment]
Got it. I just wanted to confirm! I also see the issue has already been assigned to me as well. I'll start working on this soon.
