### ISSUE TITLE
💻 Add toolip to icons on hover 

### ISSUE THREAD

**Issue by Kvaibhav01** [jayehernandez/letra-extension#90]
Currently, the icons themselves don't provide much context as to what they do. **Adding a tooltip on hover** will let the users know about each element. 

Example: Hovering over the gear icon (⚙) opens up a tooltip which says "Settings".

This will be good for accessibility and can be done via [Vuetify's tooltip component](https://vuetifyjs.com/en/components/tooltips/).

**Comment by jayehernandez** [comment]
Great feature idea @Kvaibhav01! 🔥 Really want this app to be as accessible and easy to use as possible.

Good to use Vuetify's tooltip as well. Would you like to take this on?

**Comment by Kvaibhav01** [comment]
[Yes](https://giphy.com/gifs/excited-yes-agree-jErnybNlfE1lm)

**Comment by pollyj** [comment]
Hi @jayehernandez! I'd like to work on this issue if that's okay? :)

**Comment by jayehernandez** [comment]
Hey @pollyj, sorry this issue is already assigned to @Kvaibhav01!

Hope you can check out the other issues (or open a new one!) :)

**Comment by pollyj** [comment]
@jayehernandez Got it, sorry! I'll check back (:

**Comment by tilenmiklavic** [comment]
Has this issue been resolved already? If not and there is no interest for others to work on it, I would be glad to take this task on.

**Comment by jayehernandez** [comment]
Hey @tilenmiklavic, this hasn't been resolved yet. @Kvaibhav01 mentioned that he won't be able to work on it for now. I'll assign this issue to you! Please let me know if you have any concerns.

**Comment by shubhangi013** [comment]
Is this issue open?
